# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HotelUrbanoDesafio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HotelUrbanoDesafio

  target 'HotelUrbanoDesafioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HotelUrbanoDesafioUITests' do
    # Pods for testing
  end

  pod 'SDWebImage'
  
  
end
